// <auto-generated />
using System;
using ForumService.ForumService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForumService.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20260613101207_AddVideoInPost")]
    partial class AddVideoInPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.CommentEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Upvote")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ThreadId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.CommentVoteEf", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DownVote")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentVotes");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.ForumEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForumBanner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForumImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Forums");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.ForumTagCatalogEf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ForumId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ForumId", "Name")
                        .IsUnique();

                    b.ToTable("ForumTagCatalog", (string)null);
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.ForumThreadEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorAvatar")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<Guid>("ForumId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Images")
                        .HasColumnType("text[]");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Upvote")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Videos")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ForumId");

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.ForumUserEf", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ForumId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PermissionOverrides")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ForumId");

                    b.HasIndex("ForumId");

                    b.ToTable("ForumUsers");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.OutboxMessageEf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("aggregate_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.PollEf", b =>
                {
                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.Property<string>("PollContent")
                        .HasColumnType("text");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("ThreadId", "PollContent");

                    b.ToTable("Poll", (string)null);
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.PollVoteEf", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.Property<string>("PollContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "ThreadId");

                    b.HasIndex("ThreadId");

                    b.ToTable("PollVotes");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.TagEf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ForumThreadEfId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ForumThreadEfId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.ThreadVoteEf", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DownVote")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "ThreadId");

                    b.HasIndex("ThreadId");

                    b.ToTable("ThreadVotes");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.CommentEf", b =>
                {
                    b.HasOne("ForumService.ForumService.Infrastructure.Models.CommentEf", "ParentComment")
                        .WithMany("ChildrenComments")
                        .HasForeignKey("ParentId");

                    b.HasOne("ForumService.ForumService.Infrastructure.Models.ForumThreadEf", "ThreadEf")
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("ThreadEf");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.CommentVoteEf", b =>
                {
                    b.HasOne("ForumService.ForumService.Infrastructure.Models.CommentEf", "CommentEf")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentEf");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.ForumTagCatalogEf", b =>
                {
                    b.HasOne("ForumService.ForumService.Infrastructure.Models.ForumEf", "ForumEf")
                        .WithMany()
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumEf");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.ForumThreadEf", b =>
                {
                    b.HasOne("ForumService.ForumService.Infrastructure.Models.ForumEf", "ForumEf")
                        .WithMany()
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumEf");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.ForumUserEf", b =>
                {
                    b.HasOne("ForumService.ForumService.Infrastructure.Models.ForumEf", "ForumEf")
                        .WithMany()
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumEf");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.PollEf", b =>
                {
                    b.HasOne("ForumService.ForumService.Infrastructure.Models.ForumThreadEf", "ThreadEf")
                        .WithMany("PollItems")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThreadEf");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.PollVoteEf", b =>
                {
                    b.HasOne("ForumService.ForumService.Infrastructure.Models.ForumThreadEf", "ThreadEf")
                        .WithMany("PollVotes")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThreadEf");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.TagEf", b =>
                {
                    b.HasOne("ForumService.ForumService.Infrastructure.Models.ForumThreadEf", null)
                        .WithMany("Tags")
                        .HasForeignKey("ForumThreadEfId");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.ThreadVoteEf", b =>
                {
                    b.HasOne("ForumService.ForumService.Infrastructure.Models.ForumThreadEf", "ThreadEf")
                        .WithMany("Votes")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThreadEf");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.CommentEf", b =>
                {
                    b.Navigation("ChildrenComments");
                });

            modelBuilder.Entity("ForumService.ForumService.Infrastructure.Models.ForumThreadEf", b =>
                {
                    b.Navigation("PollItems");

                    b.Navigation("PollVotes");

                    b.Navigation("Tags");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
