name: Deploy API Gateway
on:
  push:
    branches: [main]
    paths:
      - 'ApiGateway/**'
      - '.github/workflows/deploy-api-gateway.yml'
jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      service-name: api-gateway
      dockerfile-path: ApiGateway/Dockerfile
    secrets: inherit
    permissions:
      contents: read
      id-token: write
